import pygame

pygame.init()


info = pygame.display.Info()
SCREEN_WIDTH, SCREEN_HEIGHT = info.current_w, info.current_h


SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

GRAVITY = 0.4 # 0.4
FPS = 60
OCTAVES = 4 # 5


FLIP_ANIMATION_SPEED = 7
WALK_ANIMATION_SPEED = 5
SPRINT_ANIMATION_SPEED = 3
SHOOT_ANIMATION_SPEED = 4 # 4
NOAIM_SHOOT_ANIMATION_SPEED = 2
DEATH_ANIMATION_SPEED = 12
HURT_ANIMATION_SPEED = 2
STANDING_RELOAD_ANIMATION_SPEED = 4
ENEMY_SHOOT_ANIMATION_SPEED = 16

BLOCK_SIZE = 18 # 18
JUMP_CONSTANT = 0.8 # 0.8
WALKING_VEL = BLOCK_SIZE // 4.5
SPRINTING_VEL = WALKING_VEL * 2
RENDER_DISTANCE = 3
MAX_ENEMY_SHOOT_DIST = SCREEN_WIDTH // 2
MIN_ENEMY_SHOOT_DIST = SCREEN_WIDTH // 10
PLAYER_SHOOT_RANGE = 20



BULLET_SPEED = 30
SHOOTING_COOLDOWN = 8 # 2
ENEMY_SHOOTING_COOLDOWN = SHOOTING_COOLDOWN * 2
ROUNDS_IN_MAG = 30
RECOIL = 0.25
SPRAY_INNACURACY = 70
ENEMY_INNACURACY = 100
MIN_ENEMY_SPAWN_DIST = SCREEN_WIDTH // 2.5
MAX_ENEMY_SPAWN_DIST = SCREEN_WIDTH
ENEMY_RUN_DIST = MAX_ENEMY_SPAWN_DIST / 2

MAX_ENEMIES_AT_ONCE = 5

ENEMY_SPAWN_RATE = FPS  / 1.5
MAX_SPAWN_RATE = 20

HEAD_SHOT_DAMAGE = 0.35
BODY_SHOT_DAMAGE = 0.2
LEG_SHOT_DAMAGE = 0.05

STAMINA_TO_WALK = 0
STAMINA_TO_RUN = 1 / (FPS * 2)
STAMINA_TO_FLIP = 0.3
STAMINA_RECOVER_FACTOR = 1.0005
REGEN_FACTOR = STAMINA_RECOVER_FACTOR


SKY_BLUE = (135, 206, 235)
STAMINA_YELLOW = (255, 211, 0)
HEALTH_RED = (85, 0, 0)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
SURFACE_GROUND_COLOR = 	(17,124,19)
GROUND_COLOR = (65,152,10)