import pygame

pygame.init()


info = pygame.display.Info()
SCREEN_WIDTH, SCREEN_HEIGHT = info.current_w, info.current_h


SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

GRAVITY = 0.4 # 0.4
SLIDE_FRICITON = 0.2
RAIN_SLIDE_FRICTION = SLIDE_FRICITON / 2
PLAYER_MASS = GRAVITY * 8 # player is 78 kg including the gun

FRICTIONAL_FORCE = SLIDE_FRICITON * PLAYER_MASS * GRAVITY # Ff = uFn = umg
RAIN_FRICTIONAL_FORCE = RAIN_SLIDE_FRICTION * PLAYER_MASS * GRAVITY
FPS =  60
OCTAVES = 7 # 5
HEIGHT_FACTOR = 0.65


FLIP_ANIMATION_SPEED = 7
WALK_ANIMATION_SPEED = 5
SPRINT_ANIMATION_SPEED = 3
SHOOT_ANIMATION_SPEED = 4 # 4
NOAIM_SHOOT_ANIMATION_SPEED = 2
DEATH_ANIMATION_SPEED = 12
HURT_ANIMATION_SPEED = 2 # 2
STANDING_RELOAD_ANIMATION_SPEED = 4
ATTACK_ANIMATION_SPEED = 4


ENEMY_SHOOT_ANIMATION_SPEED = 16
ENEMY_HURT_ANIMATION_SPEED = 4
ENEMY_DEATH_ANIMATION_SPEED = 8


BLOCK_SIZE = 19 # 18
JUMP_CONSTANT = 0.8 # 0.8
FLING_CONSTANT = 0.5
WALKING_VEL = BLOCK_SIZE // 4.5
SPRINTING_VEL = WALKING_VEL * 2
RENDER_DISTANCE = 2
MAX_ENEMY_SHOOT_DIST = SCREEN_WIDTH * 3 // 4
MIN_ENEMY_SHOOT_DIST = BLOCK_SIZE * 6
PLAYER_SHOOT_RANGE = 35 # Angle up and down the player can shoot within



BULLET_SPEED = 30
SHOOTING_COOLDOWN = 14 # 2, 8
ENEMY_SHOOTING_COOLDOWN = SHOOTING_COOLDOWN * 2
ROUNDS_IN_MAG = 30
RECOIL = 0.25
SPRAY_INNACURACY = 70
ENEMY_INNACURACY = 35 # 100
AIMED_ACCURACY = 10
ATTACK_RANGE = BLOCK_SIZE * 3
ATTACK_COOLDOWN = 8
ATTACK_VEL_X = 1
MIN_ENEMY_SPAWN_DIST = BLOCK_SIZE * 5
MAX_ENEMY_SPAWN_DIST = SCREEN_WIDTH * 2
ENEMY_RUN_DIST = MAX_ENEMY_SPAWN_DIST / 2
MAX_ENEMIES_AT_ONCE = 4

ENEMY_SPAWN_RATE = FPS * 4 # FPS * 2.5
MAX_SPAWN_RATE = 20
BLOCKS_TILL_DIFFICULTY_INCREASE = 500
DIFFICULTY_MULTIPLIER = 3

HEAD_SHOT_DAMAGE = 0.35
BODY_SHOT_DAMAGE = 0.2
LEG_SHOT_DAMAGE = 0.05
ATTACK_DAMAGE = 0.25 # 0.25

STAMINA_TO_WALK = 0
STAMINA_TO_RUN = 1 / (FPS * 1.6) # 1 / (FPS * 1.75)
STAMINA_TO_FLIP = 0.3
STAMINA_TO_SLIDE = 0.1
STAMINA_TO_ATTACK = 0.12

STAMINA_RECOVER_FACTOR = 1.0005
REGEN_FACTOR = STAMINA_RECOVER_FACTOR


BOOST_FLOAT_SPEED = 0.5
BOOST_LIFESPAN = FPS * 7
HEALTH_BOOST_SPAWN_RATE = FPS * 600
STAMINA_BOOST_SPAWN_RATE = FPS * 550 # 600
HEALTH_BOOST = 0.25
STAMINA_BOOST = 0.18

SKY_BLUE = (135, 206, 235)
DULL_SKY = (120, 120, 120)
STAMINA_YELLOW = (255, 211, 0)
HEALTH_RED = (85, 0, 0)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
SURFACE_GROUND_COLOR = 	(17,124,19)
GROUND_COLOR = (65,152,10)